package BAI22;

import java.io.File;
import java.io.IOException;
import java.net.DatagramPacket;
import java.net.DatagramSocket;
import java.net.InetAddress;
import java.net.SocketException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Binh
 */
public class CLIENT extends javax.swing.JFrame {

    private InetAddress host;
    private int port;
    DatagramSocket client;
    public CLIENT() {
        initComponents();
        try {
            host = InetAddress.getByName("localhost");
            port = 2212;
            client = new DatagramSocket();
        } catch (SocketException ex) {
            Logger.getLogger(CLIENT.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(CLIENT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBAI1 = new javax.swing.JPanel();
        bttSourceChoose = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        lblSourcePath = new javax.swing.JLabel();
        lblDesPath = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAreaBai1 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        bttQuaylai1 = new javax.swing.JButton();
        pnlChonBai = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pnlBAI2 = new javax.swing.JPanel();
        bttLayEmail = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaEmailOut = new javax.swing.JTextArea();
        bttQuaylai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlBAI1.setBackground(new java.awt.Color(255, 204, 204));
        pnlBAI1.setPreferredSize(new java.awt.Dimension(580, 427));

        bttSourceChoose.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttSourceChoose.setForeground(new java.awt.Color(51, 51, 51));
        bttSourceChoose.setText("Source");
        bttSourceChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttSourceChooseActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 51));
        jButton3.setText("Destination");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 51));
        jButton4.setText("MOVE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtAreaBai1.setColumns(20);
        txtAreaBai1.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtAreaBai1.setRows(5);
        jScrollPane2.setViewportView(txtAreaBai1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Server:");

        bttQuaylai1.setBackground(new java.awt.Color(102, 153, 255));
        bttQuaylai1.setText("←");
        bttQuaylai1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttQuaylai1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBAI1Layout = new javax.swing.GroupLayout(pnlBAI1);
        pnlBAI1.setLayout(pnlBAI1Layout);
        pnlBAI1Layout.setHorizontalGroup(
            pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBAI1Layout.createSequentialGroup()
                .addComponent(bttQuaylai1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlBAI1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBAI1Layout.createSequentialGroup()
                        .addGroup(pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bttSourceChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSourcePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblDesPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBAI1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
            .addGroup(pnlBAI1Layout.createSequentialGroup()
                .addGap(216, 216, 216)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlBAI1Layout.setVerticalGroup(
            pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBAI1Layout.createSequentialGroup()
                .addComponent(bttQuaylai1)
                .addGap(18, 18, 18)
                .addGroup(pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblSourcePath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttSourceChoose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addGroup(pnlBAI1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBAI1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel7))
                    .addGroup(pnlBAI1Layout.createSequentialGroup()
                        .addComponent(lblDesPath, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBAI1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 400));
        pnlBAI1.setVisible(false);

        pnlChonBai.setBackground(new java.awt.Color(255, 204, 204));
        pnlChonBai.setPreferredSize(new java.awt.Dimension(541, 427));

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Bài 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 51));
        jButton2.setText("Bài 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Thực Hành Lập Trình Mạng - Buổi 2");

        javax.swing.GroupLayout pnlChonBaiLayout = new javax.swing.GroupLayout(pnlChonBai);
        pnlChonBai.setLayout(pnlChonBaiLayout);
        pnlChonBaiLayout.setHorizontalGroup(
            pnlChonBaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonBaiLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlChonBaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChonBaiLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlChonBaiLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90))))
        );
        pnlChonBaiLayout.setVerticalGroup(
            pnlChonBaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChonBaiLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlChonBaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        getContentPane().add(pnlChonBai, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));

        pnlBAI2.setBackground(new java.awt.Color(255, 204, 204));

        bttLayEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bttLayEmail.setForeground(new java.awt.Color(51, 51, 51));
        bttLayEmail.setText("Lấy email");
        bttLayEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttLayEmailActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Server:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Họ tên:");

        txtAreaEmailOut.setColumns(20);
        txtAreaEmailOut.setFont(new java.awt.Font("Monospaced", 0, 17)); // NOI18N
        txtAreaEmailOut.setRows(5);
        jScrollPane1.setViewportView(txtAreaEmailOut);

        bttQuaylai.setBackground(new java.awt.Color(102, 153, 255));
        bttQuaylai.setText("←");
        bttQuaylai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttQuaylaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBAI2Layout = new javax.swing.GroupLayout(pnlBAI2);
        pnlBAI2.setLayout(pnlBAI2Layout);
        pnlBAI2Layout.setHorizontalGroup(
            pnlBAI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBAI2Layout.createSequentialGroup()
                .addGroup(pnlBAI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBAI2Layout.createSequentialGroup()
                        .addComponent(bttQuaylai)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBAI2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlBAI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBAI2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtHoTen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bttLayEmail))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlBAI2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        pnlBAI2Layout.setVerticalGroup(
            pnlBAI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBAI2Layout.createSequentialGroup()
                .addComponent(bttQuaylai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBAI2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttLayEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(pnlBAI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, -1));
        pnlBAI2.setVisible(false);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bttSourceChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttSourceChooseActionPerformed
        JFileChooser sourceChooser = new JFileChooser();
        sourceChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        sourceChooser.setAcceptAllFileFilterUsed(false);
        int x = sourceChooser.showDialog(this, "Select");
        if (x == sourceChooser.APPROVE_OPTION) {
            File sourceFile = sourceChooser.getSelectedFile();
            lblSourcePath.setText(sourceFile.getPath());
        }
    }//GEN-LAST:event_bttSourceChooseActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFileChooser desChooser = new JFileChooser();
        desChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        desChooser.setAcceptAllFileFilterUsed(false);
        int x = desChooser.showDialog(this, "Select");
        if (x == desChooser.APPROVE_OPTION) {
            File desFile = desChooser.getSelectedFile();
            lblDesPath.setText(desFile.getPath());
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            byte[] sourcePath = lblSourcePath.getText().getBytes();
            byte[] desPath = lblDesPath.getText().getBytes();
            byte[] bai = String.valueOf("1").getBytes();
            
            DatagramPacket bai1 = new DatagramPacket(bai, bai.length, host, port);
            client.send(bai1);
            DatagramPacket sourceAddress = new DatagramPacket(sourcePath, sourcePath.length, host, port);
            client.send(sourceAddress);
            DatagramPacket desAddress    = new DatagramPacket(desPath   , desPath.length   , host, port);
            client.send(desAddress);
            
            byte[] message = new byte[1024];
            DatagramPacket kq = new DatagramPacket(message, message.length);
            client.receive(kq);
            txtAreaBai1.append(new String(message,0, message.length));
        } catch (IOException ex) {
            txtAreaBai1.setText("Lỗi truyền tin!");
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        pnlBAI2.setVisible(true);
        pnlChonBai.setVisible(false);
        pnlBAI1.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        pnlBAI1.setVisible(true);
        pnlChonBai.setVisible(false);
        pnlBAI2.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bttLayEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttLayEmailActionPerformed
        try {
            byte[] hoten = txtHoTen.getText().getBytes();
            byte[] bai = String.valueOf("2").getBytes();
            
            DatagramPacket bai2 = new DatagramPacket(bai, bai.length,host,port);
            client.send(bai2);
            DatagramPacket hotenData = new DatagramPacket(hoten, hoten.length, host, port);
            client.send(hotenData);
            
            byte[] email = new byte[1024];
            DatagramPacket emailData = new DatagramPacket(email, email.length);
            client.receive(emailData);
            txtAreaEmailOut.append(new String(email, 0, email.length));
            txtAreaEmailOut.append("\n");
        } catch (IOException ex) {
            txtAreaEmailOut.setText("Lỗi truyền tin!");
        }
    }//GEN-LAST:event_bttLayEmailActionPerformed

    private void bttQuaylaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttQuaylaiActionPerformed
        pnlBAI1.setVisible(false);
        pnlBAI2.setVisible(false);
        pnlChonBai.setVisible(true);
    }//GEN-LAST:event_bttQuaylaiActionPerformed

    private void bttQuaylai1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttQuaylai1ActionPerformed
        bttQuaylaiActionPerformed(evt);
    }//GEN-LAST:event_bttQuaylai1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLIENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLIENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttLayEmail;
    private javax.swing.JButton bttQuaylai;
    private javax.swing.JButton bttQuaylai1;
    private javax.swing.JButton bttSourceChoose;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDesPath;
    private javax.swing.JLabel lblSourcePath;
    private javax.swing.JPanel pnlBAI1;
    private javax.swing.JPanel pnlBAI2;
    private javax.swing.JPanel pnlChonBai;
    private javax.swing.JTextArea txtAreaBai1;
    private javax.swing.JTextArea txtAreaEmailOut;
    private javax.swing.JTextField txtHoTen;
    // End of variables declaration//GEN-END:variables
}
